name: CI

on:
  push:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit message
        id: msg
        run: |
          MSG=$(git log -1 --pretty=%B)
          echo "full_message<<EOF" >> $GITHUB_OUTPUT
          echo "$MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Should publish?
        id: should
        run: |
          if echo "${{ steps.msg.outputs.full_message }}" | grep -qi '\[PUBLISH\]'; then
            echo "publish=true"  >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Repository dispatch if needed
        if: steps.should.outputs.publish == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish
          client-payload: '{"version_suffix": ""}'